services:
  nginx:
    build: ./services/nginx
    image: i_nginx
    container_name: nginx-server-service
    ports:
      - 8080:80

  mariadb:
    build: ./services/mariadb
    image: i_mariadb
    container_name: mariadb-database-service
    ports:
      - 8080:80