events { }

worker_processes auto;

http {

	include /etc/nginx/mime.types;
	keepalive_timeout	70;

	server {
		listen	80;
		server_name	rduro-pe.42.fr;

		# redir to https
		return	301 https://localhost$request_uri;
		# for this to work i need to add the server name to hosts 
		#return	301 https://$server_name$request_uri;
	}

	# setting up TLS/HTTPS 
	server {
		
		# listens both on IPv4 and IPv6 on 443
		listen	443 ssl;
		listen	[::]:443 ssl;
		server_name	rduro-pe.42.fr;

		# root
		index	index.php index.html index.htm;

		ssl_protocols	TLSv1.2 TLSv1.3;
		ssl_certificate	/etc/nginx/ssl/ssl.pem;
		ssl_certificate_key	/etc/nginx/ssl/ssl.key;

		# location ~ \.php {
			# include fastcgi_params;
			# fastcgi_pass  wordpress:9000;
			# fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			# fastcgi_param QUERY_STRING    $query_string;
		# }

		location / {
			root	/usr/share/nginx/html;
			index	index.html;
		}
	}
}
