events { }

worker_processes auto;

http {
    server {
        listen       80;
        
        server_name  localhost;

        location /hello {
            root   /usr/share/nginx/html;
            index  index.html;
        }
    }

    # setting up TLS/HTTPS 
    # server {
    #     listen              443 ssl;
    #     keepalive_timeout   70;

    #     ssl_protocols       TLSv1.2 TLSv1.3;
    #     ssl_certificate     /usr/local/nginx/conf/cert.pem;
    #     ssl_certificate_key /usr/local/nginx/conf/cert.key;

        
    # }
}
