FROM mariadb:latest

# ARG VERSION=oldstable
# FROM debian:${VERSION}

# RUN apt-get update -y && apt-get upgrade -y 
# RUN apt-get install mariadb-server

# mariadb-client galera-4

# RUN mariadb-secure-installation

# COPY content /usr/share/nginx/html
# COPY conf /etc/nginx

# EXPOSE 80

# STOPSIGNAL SIGQUIT

# ENTRYPOINT ["nginx", "-g", "daemon off;"]



